name: DEPLOY TO PRODUCTION
on:
  push:
    branches: [main]
  pull_request:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Starting deploy of Myze Client (Vue.js)
        uses: actions/setup-node@master
      
      - name: Installing dependencies
        run: npm install
        
      - name: Create env file
        run: |
          touch .env
          echo VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
          echo VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> .env
          cat .env
      
      - name: Building project 
        run: npm run build
              
      - name: Deploying project to DigitalOcean
        uses: appleboy/scp-action@master
        env: 
         HOST: ${{secrets.SSH_HOST}}
         KEY: ${{secrets.SSH_KEY}}
         USERNAME: ${{secrets.SSH_USER}}
        with:
          source: "./dist"
          target: "/var/www/myze-client"
